
produtos: 
   - nome: mouse
     preco: 15.00
     cores: 
      - preto
      - branco
      - azul
   - nome: telcado
     preco: 45.00
     cores:
        - preto
        - branco
configuracoes:
  loja: Loja de acesorios para informatica.
  endereco: Rua Lauro Muller 455